### PR TITLE
Seismogram plot additions/fixes

### PR DESCRIPTION
**Pull request by megies**
This PR fixes a problem with seismogram plotting on newer matplotlib and introduces some additional features:
 - correct for time shift `t0` of source time function
 - apply uniform data scaling to synthetics when comparing with observed data
 - make it possible to select which waveforms to use (directly saved output as files `<station>.[xyz]` or differentiated output saved as `<station>.[xyz]v`)

### CODE REVIEW

**Comment by shaharkadmiel** [comment]
@megies , I am currently making commits into the 0.3.0 branch which I will eventually make into a release. Is there going to be an easy way to incorporate your current commits to master to the 0.3.0 branch?

This might be a bad form of doing things but I started elaborate api-documentation on the 0.3.0 branch and never got to actually releasing it. In the meantime, I made a lot of bug fixing and code additions on the 0.3.0 branch.

**Comment by megies** [comment]
Don't worry, we can sort it out later, it's OK for me if this doesn't get merged into master but only after your 0.3 branch is merged.

Right now I'm pretty busy, but I can stick to my local git snapshot for local work, so it's not a problem if this stays pending.

I mostly opened these PRs now, because if I don't do it right away, I won't have a good overview when coming back to all these local changes in my git repo months later.. ;-)

**Comment by shaharkadmiel** [comment]
👍

**Comment by shaharkadmiel** [comment]
Hi @megies ,
I finally got around to finalizing package-wide documentation and also added some examples, which are for now in IPython Notebook format. I've merged it into `master`.

Feel free to sort out the conflicting files and merge into `master`.
I wand to make a release and add to pip and conda. I would like to do that soon.

**Comment by megies** [comment]
Sorry, quite busy these days.. so did this merge without problems? Or did you manually merge it?

**Comment by shaharkadmiel** [comment]
I resolved some conflicts and merged.

Can you quickly remind me how to add a release to PyPi and Conda?

**Comment by megies** [comment]
Oooof.. for pypi I think it is:
```
python setup.py sdist --formats=zip upload
```
..assuming you have `~/.pypirc` set up properly..

```
[distutils] # this tells distutils what package indexes you can push to
index-servers =
    pypi
    pypitest

[pypi] # authentication details for live PyPI
repository: https://pypi.python.org/pypi
username: ...
password: ...

[pypitest] # authentication details for test PyPI
repository: https://testpypi.python.org/pypi
username: ...
password: ...
```

You can try to push to test pypi first:
```
python setup.py sdist -r pypitest --formats=zip upload
```

For conda.. did you already create a feedstock (via a PR in https://github.com/conda-forge/staged-recipes)? I don't see one..  here's an example for creating a feed stock: https://github.com/conda-forge/staged-recipes/pull/2008

**Comment by shaharkadmiel** [comment]
I'll look into conda first. Thanks!

**Pull request merged**
